export const classes = {
  pageWrapper: 'flex flex-col gap-5',
  topSection: 'flex gap-5',
  gridLayout: 'grid grid-cols-2',
  validationSection: 'm-3 grid w-full grid-cols-1 gap-4',
  bottomControls: 'flex flex-col justify-between p-3',
  cardFooter: 'flex justify-between',
  modalContent: 'flex flex-col items-center justify-center gap-4 p-4',
  currentScanWrapper: 'flex flex-col gap-4 w-full h-auto overflow-y-auto',
  gridContainer: 'grid md:grid-cols-1 lg:grid lg:grid-cols-2 gap-4',
  flexContainer: 'flex flex-col gap-4',
  createInfContainer: 'flex flex-col items-center justify-center h-full w-full p-8',
  dbDataWarning: 'flex gap-2 p-8 text-secondary bg-accent-light rounded-base',
  validationHeader:
    'flex justify-between items-center bg-(--clr-bg-2) p-3 text-base font-semibold rounded-xl',
  validationBody: 'bg-bg-1 p-3 text-sm',
  validationBodyList: 'list-none m-0 p-0',
  validationItem: 'flex justify-between items-center py-2',
  validationText: 'm-0 font-medium',
  customerDataSavedText: 'text-primary text-base font-normal',
  riskClassificationValue: 'text-(--clr-primary) text-base font-semibold ml-1',
  assignedCustomerValue: 'text-text text-base font-bold ml-1',
  wrapperCustomerDataSavedTexts: 'flex justify-center',
};
