export const classes = {
  //GDPR styles for step
  wrapper: 'relative flex flex-col gap-4 p-6',
  logoWrapper: 'absolute top-4 left-4 flex h-16 items-center',
  heading1: 'mt-16 uppercase',
  heading2: 'uppercase',
  checkboxSection: 'mt-8 flex flex-col gap-4',
  checkboxLabel: 'flex items-center gap-2',
  buttonWrapper: 'mt-6 flex justify-between',
  logoImage: 'h-16',

  //Declaration
  wrapperTitle: 'text-center w-3/5 mx-auto',
  text: 'text-lg font-bold',
  wrapperAddressSection: 'mt-8',
  checkboxSameAddress: 'mt-4',
  titleField: 'font-semibold',
  wrapperNumberAddressFields: 'flex gap-3 mb-3',
  wrapperCitizenshipSection: 'mt-8',
  wrapperFields: (numCols: number = 3) => `grid grid-cols-${numCols} gap-3 mt-3`,
  wrapperJurisdictionSection: 'mt-8',
  wrapperCheckboxSection: 'mt-8 flex justify-between',
  wrapperActions: 'flex justify-between mt-8',
  wrapperTaxPurposes: 'mt-4',
  wrapperPlaceOfResidence: 'flex gap-6',

  //survey
  heading: 'text-md font-bold',
  container: 'flex h-full flex-col p-4',
  scrollableSection: 'space-y-6 overflow-y-auto pr-2',
  headingRight: 'text-bold flex justify-end',
  headingCenter: 'text-center',
  headingLeft: 'flex justify-start',
  textBold: 'text-bold',
  sectionTitle: 'text-bold',
  checkboxGroup: 'space-y-2',
  checkboxRow3: 'grid grid-cols-3 gap-4',
  checkboxRow2: 'grid grid-cols-2 gap-4',
  divider: 'my-4 border-t border-gray-300',
  actions: 'mt-6 flex justify-between',
  sectionStartAligned: 'flex justify-start',
  sectionCentered: 'flex justify-center',
  sectionEndAligned: 'flex justify-end',
  grid3Cols: 'grid grid-cols-3 gap-4',
  grid2Cols: 'grid grid-cols-2 gap-4',
  footerActions: 'mt-6 flex justify-between',

  //peps
  scrollSection: 'space-y-6 overflow-y-auto pr-2',
  cardWrapper: 'border border-border-primary rounded-[10px] p-2 space-y-2',
  htmlContent: '',
  declarationSection: '',
  modalContent: 'flex h-full w-full flex-col items-center justify-center gap-4 text-center',
};
